### PR TITLE
discard messages incoming after stream cancellation

### LINKED ISSUE #34: Issue with race of cancelling data on client side and sending data on server side
If the client side cancels a stream and the server side sends more data at the same time, the client reacts incorrectly to the incoming data frames.

From https://github.com/grpc/grpc-dart/issues/131#issuecomment-432718640:

With the following events:

* client calls a method that streams results
* server starts the stream and send the first DataFrame
* client receives the first DataFrame
* client cancels the stream
* server (that has not yet received the cancellation) sends the second DataFrame
* server receives cancellation and stops sending DataFrame
* client receives the second DataFrame

The last line leads today to an error (grabbed with some additionnal logs):

```
Connection._catchProtocolErrors: Bad state: Was in the process of closing.
#0      _StreamMessageQueueIn&Object&TerminatableMixin&ClosableMixin.ensureNotClosingSync (package:http2/src/error_handler.dart:73:7)
#1      StreamMessageQueueIn.enqueueMessage (package:http2/src/flowcontrol/stream_queues.dart:217:5)
#2      ConnectionMessageQueueIn._tryDispatch (package:http2/src/flowcontrol/connection_queues.dart:317:10)
#3      ConnectionMessageQueueIn._addMessage (package:http2/src/flowcontrol/connection_queues.dart:295:5)
#4      ConnectionMessageQueueIn.processDataFrame (package:http2/src/flowcontrol/connection_queues.dart:253:5)
#5      StreamHandler._handleDataFrame (package:http2/src/streams/stream_handler.dart:634:19)
#6      StreamHandler._processStreamFrameInternal.<anonymous closure> (package:http2/src/streams/stream_handler.dart:596:11)
#7      _StreamHandler&Object&TerminatableMixin.ensureNotTerminatedSync (package:http2/src/error_handler.dart:33:13)
#8      StreamHandler._processStreamFrameInternal (package:http2/src/streams/stream_handler.dart:509:12)
#9      StreamHandler.processStreamFrame (package:http2/src/streams/stream_handler.dart:469:7)
#10     Connection._handleFrameImpl (package:http2/src/connection.dart:368:16)
#11     Connection._setupConnection.<anonymous closure>.<anonymous closure> (package:http2/src/connection.dart:155:34)
#12     Connection._catchProtocolErrors (package:http2/src/connection.dart:300:9)
#13     Connection._setupConnection.<anonymous closure> (package:http2/src/connection.dart:155:7)
#14     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
#15     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#16     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
#17     _rootRunUnary (dart:async/zone.dart:1132:38)
#18     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#20     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#21     _DelayedData.perform (dart:async/stream_impl.dart:584:14)
#22     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:700:11)
#23     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:660:7)
#24     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#25     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#26     _rootRun (dart:async/zone.dart:1120:38)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#29     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#30     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#31     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#35     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#36     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#37     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#38     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113:13)
#39     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166:5)
```
This leads to connection (and all its streams) closing.

IMO this second DataFrame shoud be discard. In the http2 spec I see:

> However, after sending the RST_STREAM, the sending endpoint MUST be prepared to receive and 
> process additional frames sent on the stream that might have been sent by the peer prior to the arrival 
> of the RST_STREAM.

From https://github.com/grpc/grpc-dart/issues/131#issuecomment-432718640:

There are still issue with the removal of the stream from StreamHandler._openStreams by [streams_handler.dart](https://github.com/dart-lang/http2/blob/34fc7780a196be782f50c20ccbc333075c7cb8f0/lib/src/streams/stream_handler.dart#L336-L338) . Once called the next incoming frame doesn't match any open stream and this leads to a protocol error. It looks like cancelled streams should also be tracked in this class.

### PR DESCRIPTION
**Pull request by a14n**
Fixes #34

### CODE REVIEW

**Comment by a14n** [comment]
It also seems to fix grpc/grpc-dart#111 ( /cc @sigurdm )

File: lib/src/streams/stream_handler.dart [hunk 1]
```diff
@@ -330,6 +330,13 @@ class StreamHandler extends Object with TerminatableMixin, ClosableMixin {
 
     _setupOutgoingMessageHandling(stream);
 
+    // handle incoming stream cancelation
+    streamQueueIn.onCancel.then((_) {
+      if (!streamQueueIn.wasClosed && !streamQueueIn.wasTerminated) {
+        _frameWriter.writeRstStreamFrame(streamId, ErrorCode.CANCEL);
+      }
```
Comment (mkustermann) [inline lib/src/streams/stream_handler.dart]: After reading the http/2 spec for some time this morning, it seems to me that this is not quite the right thing to do.

Let's assume we have a bi-directional stream between A and B. B now cancels the `incomingMessages` stream. Though B might still want to send more data to `A` via the `outgoingMessages` stream.

Though if `B` sends an RST.Cancel, it will cause `A` to consider the stream as closed in both directions, see the [http/2 state diagram](https://http2.github.io/http2-spec/#rfc.section.5.1), which is not what we intended.

So far I have not found any mechanism in http/2 to tell the remote end we are not interested in more data anymore without also saying that we are not interested in sending data anymore. Only the sender can cause the state to go into half-closed by sending an end-of-stream.

Maybe the best thing to do is simply drop incoming messages from the remote end and keep everything else as it is. If we end up in the "half-closed (local)" state **and** we cancelled incoming messages it is safe to send the RST.

(We could argue that canceling for `incomingMessages` is the same as terminating the stream (in which case sending an RST.Cancel frame is ok) - but this seems not quite right to me from an API point of view - a user would not expect that. We do have a `stream.terminate()` method this after all)

File: lib/src/flowcontrol/stream_queues.dart [hunk 2]
```diff
@@ -174,25 +174,25 @@ class StreamMessageQueueIn extends Object
...
+        onResume: () {
+          if (!wasClosed && !wasTerminated) {
+            _tryDispatch();
+            _tryUpdateBufferIndicator();
+          }
+        },
+        onCancel: cancel);
 
     _serverPushStreamsC = new StreamController(onListen: () {
       if (!wasClosed && !wasTerminated) {
```
Comment (mkustermann) [inline lib/src/flowcontrol/stream_queues.dart]: Looking at the code more, it appears to me that the handling of peer pushes is not correct. We have to intercept the `cancel` event here as well and respond to `PushPromiseMessage`es with RSTs when cancelled.

**Comment by mkustermann** [comment]
> It also seems to fix grpc/grpc-dart#111 ( /cc @sigurdm )

Looking at the stack from https://github.com/grpc/grpc-dart/issues/111, I don't think it will fix that issue:
```
Bad state: Cannot add event after closing
#0      _StreamController.add (dart:async/stream_controller.dart:584:24)
#1      _StreamSinkWrapper.add (dart:async/stream_controller.dart:858:13)
#2      TransportStream.sendHeaders (package:http2/transport.dart:241:10)
#3      ServerHandler.sendTrailers (package:grpc/src/server/handler.dart:301:13)
```
Here the caller in `SeverHandler.sendTrailers` in package:grpc is calling `sendHeaders` without checking `isOpen` first, so this seems clearly like a bug to me.

**Comment by a14n** [comment]
Regarding grpc/grpc-dart#111 using this http2 patch makes the issue disappear.

File: lib/src/streams/stream_handler.dart [hunk 3]
```diff
@@ -330,6 +330,17 @@ class StreamHandler extends Object with TerminatableMixin, ClosableMixin {
...
     _setupOutgoingMessageHandling(stream);
 
+    // handle incoming stream cancellation. RST is only sent when streamQueueOut
+    // has been closed because RST make the stream 'closed'.
+    streamQueueIn.onCancel.then((_) {
+      if (streamQueueIn.wasCancelled &&
+          !streamQueueIn.wasClosed &&
+          !streamQueueIn.wasTerminated &&
+          (streamQueueOut.wasClosed || streamQueueOut.wasTerminated)) {
+        _frameWriter.writeRstStreamFrame(streamId, ErrorCode.CANCEL);
```
Comment (mkustermann) [inline lib/src/streams/stream_handler.dart]: Unfortunately checking `streamQueueOut.wasClosed` is not sufficient to know that all data has been written out yet. There is a buffer in the `StreamQueueOut` as well as in the more low-level `ConnectionMessageQueueOut`: Both of them buffer data until the flow control window allows us to send the data to the underlying socket.

There is one way we can ensure the ordering, which is by adding a new `Message` type. We send it down to `StreamQueueOut` and then to `ConnectionMessageQueueOut`, which will then write the RST frame.

```dart
streamQueueIn.onCancel.then((_) {
  // If our side is done sending data, i.e. we have enqueued the end-of-steam in the
  // outgoing message queue, but the remote end is still sending us data, despite us not
  // being interested in it, we will reset the stream.
  if (stream.state == StreamState.HalfClosedLocal) {
    stream.outgoingQueue.enqueueMessage(new ResetStreamMessage(stream.id, ErrorCode.CANCEL));`
  }
});
```

(similar to how we do it with `GoawayMessage`)

That should work. Unfortunately the server will also need some fixing in this scenario, because when it receives the RST it will immediately tell the application, not delivering the data that might be in the connection/stream level buffers.


To make life easier for you, I'm perfectly fine if you don't handle the RST case for now and just drop the messages.

Comment (a14n) [reply lib/src/streams/stream_handler.dart]: Making this change the _Bad state_ error is back because we try to enqueue after closing :-(

```
ERROR: Bad state: Was in the process of closing.
package:http2/src/error_handler.dart 91:7              _StreamMessageQueueOut&Object&TerminatableMixin&ClosableMixin.ensureNotClosingSync
package:http2/src/flowcontrol/stream_queues.dart 71:5  StreamMessageQueueOut.enqueueMessage
package:http2/src/streams/stream_handler.dart 341:30   StreamHandler._newStreamInternal.<fn>
```

Comment (a14n) [reply lib/src/streams/stream_handler.dart]: I see this error in the test I added `data-frame-received-after-stream-cancel`

Comment (a14n) [reply lib/src/streams/stream_handler.dart]: >I see this error in the test I added data-frame-received-after-stream-cancel

 and also in a simple manual test I wrote

Comment (a14n) [reply lib/src/streams/stream_handler.dart]: According to https://http2.github.io/http2-spec/#StreamStates it is allowed to send R after ES. I will update the code to allow that.

File: lib/src/streams/stream_handler.dart [hunk 4]
```diff
@@ -330,6 +330,17 @@ class StreamHandler extends Object with TerminatableMixin, ClosableMixin {
 
     _setupOutgoingMessageHandling(stream);
 
+    // handle incoming stream cancellation. RST is only sent when streamQueueOut
```
[the remark this answers is not in the document]
Comment (a14n) [reply lib/src/streams/stream_handler.dart]: Done

File: lib/src/streams/stream_handler.dart (hunk 3 above)
Comment (a14n) [reply lib/src/streams/stream_handler.dart]: Done

**Comment by a14n** [comment]
PTAL

**Comment by mkustermann** [comment]
Looks good, I'll merge it :)

**Comment by mkustermann** [comment]
@sigurdm @a14n Maybe it would make sense to publish a new version?

**Comment by sigurdm** [comment]
Yes I'll make a PR.
